export const UserListColumns = [
  {
    title: "Transaction ID",
    dataIndex: "id",
    key: "id",
    width: 140,
    editable: false,
    valueDisplay: "text",
    ellipsis: true,
    sorting: true,
  },
  {
    title: "First Name",
    dataIndex: "first_name",
    key: "first_name",
    width: 140,
    editable: false,
    valueDisplay: "text",
    ellipsis: true,
    sorting: true,
  },
  {
    title: "Last Name",
    dataIndex: "last_name",
    key: "last_name",
    width: 140,
    editable: false,
    valueDisplay: "text",
    ellipsis: true,
    sorting: true,
  },
  {
    title: "Email",
    dataIndex: "email",
    key: "email",
    width: 200,
    editable: false,
    valueDisplay: "text",
    ellipsis: true,
    sorting: true,
  },
  {
    title: "Modules",
    dataIndex: "modules",
    key: "modules",
    width: 180,
    editable: false,
    valueDisplay: "tags", // assuming it's a list of modules
    ellipsis: true,
    sorting: false,
  },
  {
    title: "Company Name",
    dataIndex: "company_name",
    key: "company_name",
    width: 180,
    editable: false,
    valueDisplay: "text",
    ellipsis: true,
    sorting: true,
  },
  {
    title: "Signup Date",
    dataIndex: "signup_date",
    key: "signup_date",
    width: 160,
    editable: false,
    valueDisplay: "date", // you might format with moment/dayjs
    ellipsis: false,
    sorting: true,
  },
  {
    title: "Role",
    dataIndex: "role",
    key: "role",
    width: 140,
    editable: false,
    valueDisplay: "text",
    ellipsis: true,
    sorting: true,
  },
  {
    title: "Status",
    dataIndex: "status",
    key: "status",
    width: 120,
    editable: false,
    valueDisplay: "badge", // assuming active/inactive or similar
    ellipsis: false,
    sorting: true,
  },
];
